### ISSUE TITLE
error with find_mutants

### ISSUE THREAD

**Issue by EricFournier3** [Ellmen/alcov#61]
Hi,

I'm using version 1.1.28 and I  got the following error when running

` alcov find_mutants  samples.txt`

Searching for mutations in None
Traceback (most recent call last):
  File "/data/soft/anaconda/2021-11/envs/alcov/bin/alcov", line 8, in <module>
    sys.exit(main())
  File "/data/soft/anaconda/2021-11/envs/alcov/lib/python3.7/site-packages/alcov/command_line.py", line 6, in main
    fire.Fire(alcov.CovBreakdown)
  File "/data/soft/anaconda/2021-11/envs/alcov/lib/python3.7/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/data/soft/anaconda/2021-11/envs/alcov/lib/python3.7/site-packages/fire/core.py", line 482, in _Fire
    target=component.__name__)
  File "/data/soft/anaconda/2021-11/envs/alcov/lib/python3.7/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data/soft/anaconda/2021-11/envs/alcov/lib/python3.7/site-packages/alcov/__init__.py", line 21, in find_mutants
    find_mutants(samples_path, mutations_path=mutations_path, min_depth=min_depth, save_img=save_img, csv=csv)
  File "/data/soft/anaconda/2021-11/envs/alcov/lib/python3.7/site-packages/alcov/analyze.py", line 235, in find_mutants
    with open(mutations_path, 'r') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

I'm not sure if the mutations.txt file is mandatory in the command argument list. According to your README it is not

Thanks
Eric

**Comment by JennKnapp** [comment]
Hi Eric, 

The mutations.txt file is not required for using the "find_mutants" function, but you do need to specify either a mutations.txt file (containing a list of mutations to look for) or a name of a lineage (then the tool will look for all mutations in the constellation for that lineage in your samples). When specifying a lineage make sure you are using the same name as the names of the constellation files found in"alcov/alcov/data/constellations/".

For example you can run:
`alcov find_mutants samples.txt mutations.txt` 
or
`alcov find_mutants samples.txt JN.1-like`

I will update the README to reflect this, thank you!

Jenn
